[env]
#  TERM = "xterm-256color"
  TERM = "alacritty"

[font]
  size = 12.0

[window]
#  opacity = 0.1

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Mono"
